### ISSUE TITLE
send mail with bugs

### ISSUE THREAD

**Issue by archonwang** [drewkeller/redmine_digest#28]
redmine2.0.3  and test the plugins . when send mail with error
# 

*\* Processing project 'demo'...
Summarizing: 2012-07-30 to 2012-08-06 (7 days)
浠?2012-07-30 鍒?2012-08-05
Activity.scope: ["issues", "changesets", "news", "documents", "files", "wiki_edi
ts"]
events.count: 3
Found 3 events.
  Rendered plugins/redmine_digest/app/views/digest_mailer/digest.text.erb within
 layouts/mailer (31.3ms)
  Rendered plugins/redmine_digest/app/views/digest_mailer/digest.html.erb within
 layouts/mailer (15.6ms)
Email sent.
execution expired
undefined method `length' for true:TrueClass
C:/Test_PRJ/redmine-2.0/plugins/redmine_digest/app/controllers/digest_controller
.rb:82:in`digest_send'C:/Test_PRJ/redmine-2.0/plugins/redmine_digest/app/contro
llers/digest_controller.rb:127:in `test_email'C:/Ruby187/lib/ruby/gems/1.8/gems/
actionpack-3.2.6/lib/action_controller/metal/implicit_render.rb:4:in`send_actio
n'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_controller/metal
/implicit_render.rb:4:in `send_action'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpa
ck-3.2.6/lib/abstract_controller/base.rb:167:in`process_action'C:/Ruby187/lib/r
uby/gems/1.8/gems/actionpack-3.2.6/lib/action_controller/metal/rendering.rb:10:i
n `process_action'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/abstrac
t_controller/callbacks.rb:18:in`process_action'C:/Ruby187/lib/ruby/gems/1.8/gem
s/activesupport-3.2.6/lib/active_support/callbacks.rb:447:in `_run__520601895__p
rocess_action__152717814__callbacks'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupp
ort-3.2.6/lib/active_support/callbacks.rb:405:in`send'C:/Ruby187/lib/ruby/gems/
1.8/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callb
ack'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/cal
lbacks.rb:385:in`_run_process_action_callbacks'C:/Ruby187/lib/ruby/gems/1.8/gem
s/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `send'C:/Ruby187/lib
/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in`r
un_callbacks'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/abstract_con
troller/callbacks.rb:17:in `process_action'C:/Ruby187/lib/ruby/gems/1.8/gems/act
ionpack-3.2.6/lib/action_controller/metal/rescue.rb:29:in`process_action'C:/Rub
y187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_controller/metal/instrum
entation.rb:30:in `process_action'C:/Ruby187/lib/ruby/gems/1.8/gems/activesuppor
t-3.2.6/lib/active_support/notifications.rb:123:in`instrument'C:/Ruby187/lib/ru
by/gems/1.8/gems/activesupport-3.2.6/lib/active_support/notifications/instrument
er.rb:20:in `instrument'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.2.6/li
b/active_support/notifications.rb:123:in`instrument'C:/Ruby187/lib/ruby/gems/1.
8/gems/actionpack-3.2.6/lib/action_controller/metal/instrumentation.rb:29:in `pr
ocess_action'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_contr
oller/metal/params_wrapper.rb:206:in`process_action'C:/Ruby187/lib/ruby/gems/1.
8/gems/activerecord-3.2.6/lib/active_record/railties/controller_runtime.rb:18:in
 `process_action'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/abstract
_controller/base.rb:121:in`process'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack
-3.2.6/lib/abstract_controller/rendering.rb:45:in `process'C:/Ruby187/lib/ruby/g
ems/1.8/gems/actionpack-3.2.6/lib/action_controller/metal.rb:203:in`dispatch'C:
/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_controller/metal/rac
k_delegation.rb:14:in `dispatch'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2
.6/lib/action_controller/metal.rb:246:in`action'C:/Ruby187/lib/ruby/gems/1.8/ge
ms/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:73:in `call'C:/Ruby
187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/routing/route_se
t.rb:73:in`dispatch'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/acti
on_dispatch/routing/route_set.rb:36:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/j
ourney-1.0.4/lib/journey/router.rb:68:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems
/journey-1.0.4/lib/journey/router.rb:56:in `each'C:/Ruby187/lib/ruby/gems/1.8/ge
ms/journey-1.0.4/lib/journey/router.rb:56:in`call'C:/Ruby187/lib/ruby/gems/1.8/
gems/actionpack-3.2.6/lib/action_dispatch/routing/route_set.rb:600:in `call'C:/R
uby187/lib/ruby/gems/1.8/gems/rack-openid-1.3.1/lib/rack/openid.rb:98:in`call'C
:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware
/best_standards_support.rb:17:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-1.
4.1/lib/rack/etag.rb:23:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-1.4.1/li
b/rack/conditionalget.rb:25:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpac
k-3.2.6/lib/action_dispatch/middleware/head.rb:14:in`call'C:/Ruby187/lib/ruby/g
ems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware/params_parser.rb:21
:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch
/middleware/flash.rb:242:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-1.4.1/l
ib/rack/session/abstract/id.rb:205:in `context'C:/Ruby187/lib/ruby/gems/1.8/gems
/rack-1.4.1/lib/rack/session/abstract/id.rb:200:in`call'C:/Ruby187/lib/ruby/gem
s/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware/cookies.rb:338:in `ca
ll'C:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-3.2.6/lib/active_record/query_
cache.rb:64:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/activerecord-3.2.6/lib/ac
tive_record/connection_adapters/abstract/connection_pool.rb:473:in`call'C:/Ruby
187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware/callb
acks.rb:28:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/ac
tive_support/callbacks.rb:405:in`_run__397314981__call__4__callbacks'C:/Ruby187
/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:
in `send'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_suppor
t/callbacks.rb:405:in`__run_callback'C:/Ruby187/lib/ruby/gems/1.8/gems/activesu
pport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'C:/Ruby1
87/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81
:in`send'C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_suppo
rt/callbacks.rb:81:in `run_callbacks'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpac
k-3.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in`call'C:/Ruby187/lib/r
uby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware/remote_ip.rb:3
1:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatc
h/middleware/debug_exceptions.rb:16:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems/a
ctionpack-3.2.6/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'C:
/Ruby187/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/rack/logger.rb:26:in`c
all_app'C:/Ruby187/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/rack/logger.r
b:16:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_disp
atch/middleware/request_id.rb:22:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems/rack
-1.4.1/lib/rack/methodoverride.rb:21:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/
rack-1.4.1/lib/rack/runtime.rb:17:in`call'C:/Ruby187/lib/ruby/gems/1.8/gems/act
ivesupport-3.2.6/lib/active_support/cache/strategy/local_cache.rb:72:in `call'C:
/Ruby187/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/lock.rb:15:in`call'C:/Ruby1
87/lib/ruby/gems/1.8/gems/actionpack-3.2.6/lib/action_dispatch/middleware/static
.rb:62:in `call'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-cache-1.2/lib/rack/cache/
context.rb:136:in`forward'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-cache-1.2/lib/
rack/cache/context.rb:245:in `fetch'C:/Ruby187/lib/ruby/gems/1.8/gems/rack-cache
-1.2/lib/rack/cache/context.rb:185:in`lookup'C:/Ruby187/lib/ruby/gems/1.8/gems/
rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'C:/Ruby187/lib/ruby/gems/1
.8/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in`call'C:/Ruby187/lib/ruby
/gems/1.8/gems/railties-3.2.6/lib/rails/engine.rb:479:in `call'C:/Ruby187/lib/ru
by/gems/1.8/gems/railties-3.2.6/lib/rails/application.rb:220:in`call'C:/Ruby187
/lib/ruby/gems/1.8/gems/rack-1.4.1/lib/rack/content_length.rb:14:in `call'C:/Rub
y187/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/rack/log_tailer.rb:17:in`c
all'C:/Ruby187/lib/ruby/gems/1.8/gems/thin-1.4.1/lib/thin/connection.rb:80:in `p
re_process'C:/Ruby187/lib/ruby/gems/1.8/gems/thin-1.4.1/lib/thin/connection.rb:7
8:in`catch'C:/Ruby187/lib/ruby/gems/1.8/gems/thin-1.4.1/lib/thin/connection.rb:
78:in `pre_process'C:/Ruby187/lib/ruby/gems/1.8/gems/thin-1.4.1/lib/thin/connect
ion.rb:53:in`process'C:/Ruby187/lib/ruby/gems/1.8/gems/thin-1.4.1/lib/thin/conn
ection.rb:38:in `receive_data'C:/Ruby187/lib/ruby/gems/1.8/gems/eventmachine-0.1
2.10/lib/eventmachine.rb:256:in`run_machine'C:/Ruby187/lib/ruby/gems/1.8/gems/e
ventmachine-0.12.10/lib/eventmachine.rb:256:in `run'C:/Ruby187/lib/ruby/gems/1.8
/gems/thin-1.4.1/lib/thin/backends/base.rb:63:in`start'C:/Ruby187/lib/ruby/gems
/1.8/gems/thin-1.4.1/lib/thin/server.rb:159:in `start'C:/Ruby187/lib/ruby/gems/1
.8/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in`run'C:/Ruby187/lib/ruby/gems/
1.8/gems/rack-1.4.1/lib/rack/server.rb:265:in `start'C:/Ruby187/lib/ruby/gems/1.
8/gems/railties-3.2.6/lib/rails/commands/server.rb:70:in`start'C:/Ruby187/lib/r
uby/gems/1.8/gems/railties-3.2.6/lib/rails/commands.rb:55C:/Ruby187/lib/ruby/gem
s/1.8/gems/railties-3.2.6/lib/rails/commands.rb:50:in `tap'C:/Ruby187/lib/ruby/g
ems/1.8/gems/railties-3.2.6/lib/rails/commands.rb:50script/rails:6:in`require's
cript/rails:6
undefined method `length' for true:TrueClass:
Redirected to http://localhost:3000/settings/plugin/redmine_digest
Completed 302 Found in 30438ms (ActiveRecord: 218.8ms)

How to fix it? thanks.

**Comment by cprevotaux** [comment]
Same problem here. 

I hope this gets fixed.

**Comment by tamtamchik** [comment]
+1
