### ISSUE TITLE
Get_recipients crashes if project member is a group

### ISSUE THREAD

**Issue by Webovani** [drewkeller/redmine_digest#31]
If member.user_id points to Group, member.user is nil and DigestMailer.get_recipients crashes.

```
Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:166:in `get_recipients'
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:164:in `each'
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:164:in `get_recipients'
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:213:in `digests'
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:194:in `each'
/Users/bubak/rails/redmine-1.3.3/vendor/plugins/redmine_digest/app/models/digest_mailer.rb:194:in `digests'
```

**Comment by janthurau** [comment]
Should be fixed by PR #37
