### ISSUE TITLE
Error in db:migrate_plugins

### ISSUE THREAD

**Issue by bsides** [drewkeller/redmine_digest#6]
I'm getting the following error after running rake db:migrate_plugins RAILS_ENV=production. I don't know if it's a problem related to redmine_digest or not but if you could help I'd really appreciate it. My server is a Ubuntu 11 VPS with LAMP and Redmine already running (http://pro.bsides.co).

Thank you!

(in /usr/share/redmine)
rake aborted!
undefined method `safe_attributes' for #<Class:0xb6e1c178>
/usr/lib/ruby/1.8/active_record/base.rb:1959:in`method_missing'
/usr/share/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:15:
in `included'
/usr/share/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:10:
in`class_eval'
/usr/share/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:10:
in `included'
/usr/share/redmine/vendor/plugins/redmine_digest/init.rb:17:in`include'
/usr/share/redmine/vendor/plugins/redmine_digest/init.rb:17:in `send'
/usr/share/redmine/vendor/plugins/redmine_digest/init.rb:17:in`evaluate_init_rb'
/usr/lib/ruby/1.8/active_support/callbacks.rb:182:in `call'
/usr/lib/ruby/1.8/active_support/callbacks.rb:182:in`evaluate_method'
/usr/lib/ruby/1.8/active_support/callbacks.rb:166:in `call'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in`run'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `each'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in`send'
/usr/lib/ruby/1.8/active_support/callbacks.rb:90:in `run'
/usr/lib/ruby/1.8/active_support/callbacks.rb:276:in`run_callbacks'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:51:in `send'
/usr/lib/ruby/1.8/action_controller/dispatcher.rb:51:in`run_prepare_callbacks'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:631:in `prepare
_dispatcher'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:185:in`process
'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:113:in `send'
/usr/share/redmine/config/../vendor/rails/railties/lib/initializer.rb:113:in`run'
/usr/share/redmine/config/environment.rb:50
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/lib/ruby/1.8/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/1.8/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/1.8/active_support/dependencies.rb:156:in `require'
/usr/share/redmine/vendor/plugins/redmine_digest/lib/tasks/digest.rake:31
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/1.8/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/1.8/active_support/dependencies.rb:145:in `load'
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:8
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:8:in`each'
/usr/share/redmine/vendor/rails/railties/lib/tasks/rails.rb:8
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/share/redmine/Rakefile:10
/usr/lib/ruby/1.8/rake.rb:2383:in `load'
/usr/lib/ruby/1.8/rake.rb:2383:in`raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2017:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2016:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2000:in`run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in`run'
/usr/bin/rake:28

**Comment by JIMPomat** [comment]
I have the same problem

My Server is a Debian Linux 6.0...redmine works well without this plugin

rake aborted!
undefined method `safe_attributes' for #<Class:0x7fb047d04d38>
/var/lib/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:1959:in`method_missing'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:15:in `included'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:10:in`class_eval'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/lib/redmine_digest/user_patch.rb:10:in `included'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/init.rb:17:in`include'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/init.rb:17:in `send'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/init.rb:17:in`evaluate_init_rb'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:182:in `call'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:182:in`evaluate_method'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:166:in `call'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:90:in`run'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:90:in `each'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:90:in`send'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:90:in `run'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/callbacks.rb:276:in`run_callbacks'
/var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:51:in `send'
/var/lib/gems/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:51:in`run_prepare_callbacks'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:631:in `prepare_dispatcher'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:185:in`process'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`run'
/home/REDMINE/redmine/config/environment.rb:23
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/home/REDMINE/redmine/vendor/plugins/redmine_digest/lib/tasks/digest.rake:31
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
/var/lib/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:145:in `load'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:8
/var/lib/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:8:in`each'
/var/lib/gems/1.8/gems/rails-2.3.5/lib/tasks/rails.rb:8
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
/home/REDMINE/redmine/Rakefile:10
/usr/lib/ruby/1.8/rake.rb:2387:in `load'
/usr/lib/ruby/1.8/rake.rb:2387:in`raw_load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2021:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2072:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2020:in `load_rakefile'
/usr/lib/ruby/1.8/rake.rb:2004:in`run'
/usr/lib/ruby/1.8/rake.rb:2072:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2002:in`run'
/usr/bin/rake:28

Thanks for your help!
