### ISSUE TITLE
Some strange test results

### ISSUE THREAD

**Issue by spierluigi** [drewkeller/redmine_digest#9]
I am testing the plugin in development environment (redmine 1.2.0), launching the rake manually

With ‘days to include’ =1 and ‘days ago to start’  =1, I tried:

<pre>
  /usr/bin/rake redmine:send_digest start=1 days=2 project=test-uno RAILS_ENV="development"
</pre>

with this result:

<pre>
  Start: 1
  Days : 2
  ** Processing project 'test 1'...
  Summarizing: 2011-09-18 to 2011-09-20 (2 days)
  From 09/18/2011 to 09/19/2011
  Found 3 events.
  Email sent.
  The email does not have a subject, so it is assumed something went wrong.
  Digest done.
</pre>

With ‘days to include’ =7 and ‘days ago to start’  =8 I have also tried:

<pre>
  redmine:send_digest RAILS_ENV="development"
</pre>

with this result:

<pre>
  Start: 8
  Days : 7
  No projects were found in the environment or no projects have digest enabled.
  Digest done.
</pre>

All the messages refers to situations (no subject, no digest enabled) that I am not able to configure.

And also sending the test mail through the configuration panel, the system displays that  "There was no resulting email."

What am I missing ?

**Comment by spierluigi** [comment]
I have enabled a project (I haven't seen the new flag: my fault, but it isn't mentioned in the doc), but sending a digest for all (only one) projects through the config panel I get thit error:

<pre>
ArgumentError in DigestController#send_all

wrong number of arguments (2 for 1)
RAILS_ROOT: /usr/share/redmine_dev

Application Trace | Framework Trace | Full Trace
/usr/share/redmine_dev/vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:74:in `error'
/usr/share/redmine_dev/vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:74:in `digest_send'
/usr/share/redmine_dev/vendor/plugins/redmine_digest/app/controllers/digest_controller.rb:89:in `send_all'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:1333:in `send'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:1333:in `perform_action_without_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/filters.rb:617:in `call_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/lib/gems/1.8/gems/activesupport-2.3.11/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/flash.rb:151:in `perform_action'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:532:in `send'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:532:in `process_without_filters'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/filters.rb:606:in `process'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:391:in `process'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/base.rb:386:in `call'
/var/lib/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:438:in `call'
</pre>

**Comment by spierluigi** [comment]
After having enabled a project, the rake seems working, but:
- the global send from the panels gives the above error
- the rake job hasn't changed his behaviuor

Is there a way to select events to include in the project digest ?

Thank you very much for your patient ....

**Comment by drewkeller** [comment]
You have to enable the digest for each project that you want to have a 
digest processed. Digest is one of the modules you can enable in the 
project's own settings page. In your first example, you specifically 
included a project.

Where you got a warning due to the email missing a subject, did you 
receive an email or no?

If you want to see more debug messages, switch to the extra_debug branch 
and download it.

**Comment by spierluigi** [comment]
Using rake, when I received the missing subject mail i didn't receive any message (both for all projects or a single one)

In the configuration panel, the item "Send a test email to your email address" works, while the item "Send digests for all digest-enabled projects" get the error I enclosed above
